version: '3'
services:
        app:
                build: .
                image: pulpan92/flask
        production:
                image: pulpan92/flask:1
                volumes:
                        - .:/code
                command: python app.py
                ports:
                        - "80:80"
